/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module deco_7seg ( v, a,b,c,d,e,f,g);
  input [3:0]v;
  output a;
  output b;
  output c;
  output d;
  output e;
  output f;
  output g;
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  assign s2 = ~ v[3];
  assign s1 = ~ v[2];
  assign s0 = ~ v[1];
  assign s3 = ~ v[0];
  assign a = ((v[0] & s0 & s1 & s2) | (s3 & s0 & v[2]));
  assign b = ((v[0] & s0 & v[2]) | (s3 & v[1] & v[2]));
  assign c = (s3 & v[1] & s1);
  assign d = ((v[0] & s0 & s1 & s2) | (s3 & s0 & v[2]) | (v[0] & v[1] & v[2]));
  assign e = (v[0] | (s0 & v[2]));
  assign f = ((v[0] & s1 & s2) | (v[0] & v[1]) | (v[1] & s1));
  assign g = ((v[0] & v[1] & v[2]) | (s0 & s1 & s2));
endmodule
