/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module sum (
  input B,
  input A,
  input Cin,
  output Cout,
  output S
);
  assign S = ((B ^ A) ^ Cin);
  assign Cout = ((A & B) | ((B | A) & Cin));
endmodule


module full_sum (
  input a0,
  input a2,
  input a1,
  input a3,
  input b0,
  input b1,
  input b2,
  input b3,
  input Cin,
  output s0,
  output s1,
  output s2,
  output s3,
  output s4
);
  wire s5;
  wire s6;
  wire s7;
  // sum
  sum sum_i0 (
    .B( b0 ),
    .A( a0 ),
    .Cin( Cin ),
    .Cout( s5 ),
    .S( s0 )
  );
  // sum
  sum sum_i1 (
    .B( b1 ),
    .A( a1 ),
    .Cin( s5 ),
    .Cout( s6 ),
    .S( s1 )
  );
  // sum
  sum sum_i2 (
    .B( b2 ),
    .A( a2 ),
    .Cin( s6 ),
    .Cout( s7 ),
    .S( s2 )
  );
  // sum
  sum sum_i3 (
    .B( b3 ),
    .A( a3 ),
    .Cin( s7 ),
    .Cout( s4 ),
    .S( s3 )
  );
endmodule
/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module bcd7seg_hex (
  input a1,
  input b1,
  input c1,
  input d1,
  output a,
  output b,
  output c,
  output d,
  output e,
  output f,
  output g
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  assign s0 = ~ a1;
  assign s1 = ~ b1;
  assign s2 = ~ c1;
  assign s3 = ~ d1;
  assign a = ((s0 & s1 & s2 & d1) | (a1 & s1 & c1 & d1) | (a1 & b1 & s2) | (b1 & s2 & s3));
  assign b = ((s0 & b1 & s2 & d1) | (a1 & c1 & d1) | (a1 & b1 & s3) | (b1 & c1 & s3));
  assign c = ((s0 & s1 & c1 & s3) | (a1 & b1 & s3) | (a1 & b1 & c1));
  assign d = ((s0 & s1 & s2 & d1) | (s0 & b1 & s2 & s3) | (a1 & s1 & c1 & s3) | (b1 & c1 & d1));
  assign e = ((s0 & d1) | (s0 & b1 & s2) | (s1 & s2 & d1));
  assign f = ((s0 & s1 & d1) | (s0 & s1 & c1) | (s0 & c1 & d1) | (a1 & b1 & s2));
  assign g = ((s0 & s1 & s2) | (s0 & b1 & c1 & d1));
endmodule


module full_sum_4bit (
  input a0,
  input a2,
  input a1,
  input a3,
  input b0,
  input b1,
  input b2,
  input b3,
  input Cin,
  output Cout,
  output a,
  output b,
  output c,
  output d,
  output e,
  output f,
  output g
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  full_sum full_sum_i0 (
    .a0( a0 ),
    .a2( a1 ),
    .a1( a2 ),
    .a3( a3 ),
    .b0( b0 ),
    .b1( b1 ),
    .b2( b2 ),
    .b3( b3 ),
    .Cin( Cin ),
    .s0( s0 ),
    .s1( s1 ),
    .s2( s2 ),
    .s3( s3 ),
    .s4( Cout )
  );
  // bcd7seg_hex
  bcd7seg_hex bcd7seg_hex_i1 (
    .a1( s0 ),
    .b1( s1 ),
    .c1( s2 ),
    .d1( s3 ),
    .a( a ),
    .b( b ),
    .c( c ),
    .d( d ),
    .e( e ),
    .f( f ),
    .g( g )
  );
endmodule
