/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module sum (
  input B,
  input A,
  input Cin,
  output Cout,
  output S
);
  assign S = ((B ^ A) ^ Cin);
  assign Cout = ((A & B) | ((B | A) & Cin));
endmodule


module full_sum (
  input a0,
  input a2,
  input a1,
  input a3,
  input b0,
  input b1,
  input b2,
  input b3,
  input Cin,
  output s0,
  output s1,
  output s2,
  output s3,
  output s4
);
  wire s5;
  wire s6;
  wire s7;
  // sum
  sum sum_i0 (
    .B( b0 ),
    .A( a0 ),
    .Cin( Cin ),
    .Cout( s5 ),
    .S( s0 )
  );
  // sum
  sum sum_i1 (
    .B( b1 ),
    .A( a1 ),
    .Cin( s5 ),
    .Cout( s6 ),
    .S( s1 )
  );
  // sum
  sum sum_i2 (
    .B( b2 ),
    .A( a2 ),
    .Cin( s6 ),
    .Cout( s7 ),
    .S( s2 )
  );
  // sum
  sum sum_i3 (
    .B( b3 ),
    .A( a3 ),
    .Cin( s7 ),
    .Cout( s4 ),
    .S( s3 )
  );
endmodule
