/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module bcd7seg (
  input a1,
  input b1,
  input c1,
  input d1,
  output a,
  output b,
  output c,
  output d,
  output e,
  output f,
  output g
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  assign s0 = ~ a1;
  assign s1 = ~ b1;
  assign s2 = ~ c1;
  assign s3 = ~ d1;
  assign a = ((s0 & s1 & s2 & d1) | (b1 & s2 & s3));
  assign b = ((b1 & s2 & d1) | (b1 & c1 & s3));
  assign c = (s0 & s1 & c1 & s3);
  assign d = ((s0 & s1 & s2 & d1) | (b1 & s2 & s3) | (b1 & c1 & d1));
  assign e = ((s0 & b1 & s2) | d1);
  assign f = ((s0 & s1 & d1) | (s1 & c1) | (c1 & d1));
  assign g = ((s0 & s1 & s2) | (b1 & c1 & d1));
endmodule
